#!/bin/bash
SCRIPT_ABS_FILENAME=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`

dryrun=""
 
while getopts ":r" opt; do
  case $opt in
    r)
      dryrun="-r "
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
shift $((OPTIND-1))


if [ -z "$1" ]
then
  echo "Usage: $SCRIPT_ABS_FILENAME top_dir"
  exit 1
fi

nberror=0

find "$1" -type f -perm /111 -exec sh -c "file {} | grep -q "Mach-O"" \; -print | xargs -n 1 "$SCRIPT_DIR"/update_lib_path $dryrun

echo $?