#!/bin/bash


export GMP_SOURCES_DIR="gmp-4.3.2"
export MPFR_SOURCES_DIR="mpfr-2.4.2"
export MPC_SOURCES_DIR="mpc-0.8.1"
export ISL_SOURCES_DIR="isl-0.12.2"
export CLOOG_SOURCES_DIR="cloog-0.18.1"
export BINUTILS_SOURCES_DIR="binutils-2.25"
export GCC_SOURCES_DIR="gcc-4.9.4"

export TARGET_PLATFORM=x86_64-apple-darwin
export PROGRAM_SUFFIX=-4.9.4